spring:
  # Active profile setting
  profiles:
    active: development

  # REST API basePath
  data:
    rest:
      base-path: /api

  # Spring Data JPA settings
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  # Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

# Tomcat server settings
server:
  port: 8080

---
# Development
spring:
  profiles: development

  # h2 database settings
  h2:
    console:
      enabled: true
      path: /h2-console

  # Initialize the datasource with available DDL and DWL scripts
  datasource:
    initialization-mode: always

# Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
